### ISSUE TITLE
(erb):33:in `get_binding': undefined method `num_lines' for <Rake::FileTask  => []>:Rake::FileTask (NoMethodError)

### ISSUE THREAD

**Issue by toamitkumar** [relevance/rcov#13]
We are getting binding failure while executing rcov. The full stack trace:

(erb):33:in `get_binding': undefined method`num_lines' for <Rake::FileTask  => []>:Rake::FileTask (NoMethodError)
        from /usr/local/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.2/lib/rcov/formatters/html_erb_template.rb:122:in `get_binding'
        from /usr/local/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.2/lib/rcov/formatters/html_erb_template.rb:20:in`render'
        from /usr/local/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.2/lib/rcov/formatters/html_coverage.rb:93:in `create_file'
        from /usr/local/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.2/lib/rcov/formatters/html_coverage.rb:93:in`open'
        from /usr/local/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.2/lib/rcov/formatters/html_coverage.rb:93:in `create_file'
        from /usr/local/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.2/lib/rcov/formatters/html_coverage.rb:31:in`execute'
        from /usr/local/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.2/lib/rcov/formatters/base_formatter.rb:58:in `each'
        from /usr/local/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.2/lib/rcov/formatters/base_formatter.rb:58:in`each_file_pair_sorted'
        from /usr/local/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.2/lib/rcov/formatters/html_coverage.rb:30:in `execute'
        from /usr/local/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.2/lib/rcov.rb:661:in`dump_coverage_info'
        from /usr/local/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.2/lib/rcov.rb:661:in `each'
        from /usr/local/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.2/lib/rcov.rb:661:in`dump_coverage_info'
        from /usr/local/lib/ruby/gems/1.8/gems/relevance-rcov-0.8.3.2/bin/rcov:402
        from /srv/cruise/projects/profiles/work/vendor/plugins/rspec/lib/spec/runner.rb:45

**Comment by toamitkumar** [comment]
Ruby version being used:
cruise@amdc-npncruise-lx01:/srv/cruise/projects/profiles/work> ruby -v
ruby 1.8.7 (2008-08-11 patchlevel 72) [i686-linux]

**Comment by mchung** [comment]
I've run into this problem as well. 

The error message is reported during the ERB generation. The .erb file itself references a variable called +file+, which is setup by HTMLCoverage#create_file:

http://github.com/relevance/rcov/blob/eca4e2dc738920fba7c68701b60a7cc03405eb62/lib/rcov/formatters/html_coverage.rb#L86

The problem is: in the +create_file+ method, the type of +file+ is (correctly) Rcov::FileStatistics, however, in the .erb file, the type of +file+ is (incorrectly) Rake::FileTask.

Some weird naming conflict appears to occurring. 

My workaround is to rename all instances of +file+ to +fileinfo+ and update the create_file method to set +fileinfo+ instead of +file+

Edit: Remove irrelevant portion of comment.  I managed to get this working. Is the approach I'm taking (renaming instances of +file+ to +fileinfo+) acceptable?  If so, I can fork and fix.

-Marc

**Comment by mchung** [comment]
I have forked and fixed this over at http://github.com/mchung/rcov

**Comment by abedra** [comment]
Thanks!  I will take a look at the patch and get things pulled in ASAP!

**Comment by mchung** [comment]
Thanks abedra. To everyone else, I'll keep my branch open till the patch is accepted/rejected.

**Comment by abedra** [comment]
Your patch has been pulled.  I also bumped the version to 0.8.3.4. You can get the fixes by installing that version or just installing the gem directly from source.  Thanks for your help!

**Comment by toamitkumar** [comment]
Thanks a lot guys... saved my day.. !

**Comment by toamitkumar** [comment]
I tried installing the gem directly, but it seems to install the older 0.8.3.3 version...

**Comment by mchung** [comment]
Doesn't look like it's been generated yet.

abedra, can you rebuild the rubygem? (hit ruby icon, click "rebuild latest rubygem") i had to do this as well.

**Comment by abedra** [comment]
Done.  Hopefully it generates soon.  It looks like the builder is down right now

**Comment by toamitkumar** [comment]
Awesome Works... !!
