### ISSUE TITLE
Encapsulate executable (bin/rcov)

### ISSUE THREAD

**Issue by ghost** [relevance/rcov#38]
It would be nice if the executable were split into two layers -- a CLI layer and an underlying App/Session layer. This way the underlying layer can be used via Ruby code, without having to shell out to the command-line to achieve the same thing.

**Comment by ghost** [comment]
RCov has rake tasks available for you to call.  Can you just use those or are you looking for something more specific?

**Comment by rubyworks** [comment]
Actually that's the point. I don;t use Rake. I use another tool called Syckle and I want to add a plugin to Syckle to support RCov.

**Comment by trans** [comment]
Not sure why you didn't accept my Session patch. It made the top-level interface to RCov so much more comprehensible.

**Comment by abedra** [comment]
I haven't gotten around to fully testing this.  If you can provide a sample that uses Syckle it would help my testing.

**Comment by gnufied** [comment]
+1 . I was at loss for running rcov via ruby code (i.e without shelling out another ruby process). Apart from usecase mentioned by rubyworks, I had my tests running in Process.fork {} for parallelization, I am still loading entire Rails environment in each forked process, but at least with Process.fork{} I have some handle on which DB to use in each forked process and stuff. With shelling out via rake, my tests are gonna use default database and going to run over each other (and hence DB locks and issues while running tests).

In fact, I tried using CodeCoverageAnalyzer class like:

```
$code_coverage_analyzer.install_hook()
 # load rails environment
 # load test files
$code_coverage_analyzer.remove_hook()
# dump stuff
```

It was sorta working, but I noticed coverage was off the radar.

**Comment by trans** [comment]
@abedra Sorry that this fell to the way side --so much to do, so little time to do it.

The Syckle task shells out (I was hopping to rewrite it with this change), so that would not be suffice as a test. I should have written one when I first did this. Oh well. It may be too late now anyway... if the API has changed much since I first did this it might be easier to just redo it. To clarify, all I did was split the executable code into two layers, one to handle parsing the commandline options and another to actually invoke rcov analysis (a class I called `Session` for a lack of a better name). I'm sure you could re-implement the same split in an hour or so.

It would be a nice feature to have because it would allow rcov to be easily run from Ruby without shelling out. So I hope you can eventually implement it.

I wish I had more time to contribute, but I desperately need to complete some other projects, so I have to leave it there.
