### ISSUE TITLE
[Solution] : RCov installtion problem in windows 7

### ISSUE THREAD

**Issue by nkapser** [relevance/rcov#47]
Hey hi, 
# I am trying to install rcov gem on my windows 7, but it seems to expect nmake.exe file. But, when i tried to put visual studio bin(which has both nmake.exe and cl.exe) in the environment variables, it throws up the following error. If anyone has faced the same problem please let me know.

C:\Windows\system32>gem install relevance-rcov --source http://gems.github.com
Building native extensions.  This could take a while...
ERROR:  Error installing relevance-rcov:
        ERROR: Failed to build gem native extension.

C:/Ruby/bin/ruby.exe extconf.rb
creating Makefile

nmake

Microsoft (R) Program Maintenance Utility Version 9.00.30729.01
Copyright (C) Microsoft Corporation.  All rights reserved.

```
    C:\Ruby\bin\ruby -e "puts 'EXPORTS', 'Init_rcovrt'"  > rcovrt-i386-mswin32.def
    cl -nologo -I. -IC:/Ruby/lib/ruby/1.8/i386-mswin32 -IC:/Ruby/lib/ruby/1.8/i386-mswin32 -I1.8/ -MD -Zi -O2b2xg- -G6  -c -Tc1.8//callsite.c
```

NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio 9.0\VC\bin\cl.EXE"' : return code '0xc0000135'
Stop.

Gem files will remain installed in C:/Ruby/lib/ruby/gems/1.8/gems/relevance-rcov-0.9.2.1 for inspection.
Results logged to C:/Ruby/lib/ruby/gems/1.8/gems/relevance-rcov-0.9.2.1/ext/rcovrt/gem_make.out
# 

SOLUTION:
Got fixed once I downloaded the development kit from http://rubyinstaller.org/download.html . Development kit was having the all the required c++ compilers.

Thanks
-kapser.

**Comment by ghost** [comment]
Windows is not supported in this version of RCov.  There are currently no windows builds available.  I am more than happy to accept patches back to the project to make the windows version work correctly.  Please note that you are also using an outdated version of RCov.  Github no longer builds gems, and the official gem is now at gemcutter.org.

**Comment by mkosma** [comment]
Looks like I got gem install relevance-rcov to work in windows.  This was a pain, so thought I'd share.
1. Install MS Visual C++ Express 10.0
2. From command prompt, run vcvars32.bat to set environment for MSVC command line cl.exe 
3. Tweak lib/ruby/1.8/i386-mswin32/config.h to trap _MSC_VER < 1200 instead of _MSC_VER != 1200
4. Tweak lib/ruby/1.8/i386-mswin32/env.h to export ruby_frame by inserting __declspec(dllimport) between "extern" and "struct FRAME" as follows:

extern __declspec(dllimport) struct FRAME ...

I did that, and now gem install relevance-rcov --source http://gems.github.com works!

monty
