### ISSUE TITLE
Ruby 1.9 support

### ISSUE THREAD

**Issue by ghost** [relevance/rcov#8]
I have started a fork on github and have some of Rcov working with ruby 1.9. 

I have most of the pure-ruby implementation working and I re-wrote parts of the C extension that compile and run in 1.9, although they don&rsquo;t pass all the tests yet. 

Once I get it the pure ruby and C extension passing all the tests I can put in a pull request and/or make a git patch, however you guys want it.

[original LH ticket](http://relevance.lighthouseapp.com/projects/16869/tickets/4)

 This ticket has 0 attachment(s).

**Comment by ghost** [comment]
**Ruby 1.9 support**

Just a heads up....this has been merged into a 1.9 branch into spicycode-rcov, AFAIK.

 by Rob Sanheim

**Comment by rggjan** [comment]
Seems to work quite well with the --no-rcovrt option.

The only thing I can see, until now, is that "return" statements are painted red instead of green.

So here:

1 def get_name
2 return "name"
3 end

The line 2 and 3 are red, while here:

1 def get_name
2 return "name"
3 end

all is green as it should be.

**Comment by mattyoho** [comment]
Using Ruby 1.9.1, Rails 2.3.5, RSpec 1.2.9, the --no-rcovrt option blows up with:

/usr/local/lib/ruby19/gems/1.9.1/gems/relevance-rcov-0.9.2.1/lib/rcov/code_coverage_analyzer.rb:160:in `+': nil can't be coerced into Fixnum (TypeError)

Running without that option yields apparently incorrectly low coverage numbers, such as marking classes as not covered despite having been spec'd.

**Comment by stuart** [comment]
I hacked a fix to this with changing line 160 to:
cov_arr.each_with_index{|x,i| dest[i] += x.to_i}

I should write a test and generate a patch. Will do when I have a moment.
I've looked at the c code but haven't had time to figure out much there. I note that several tests don't pass in ruby 1.9.1 I'll live with slow coverage for a bit.

**Comment by evanworley** [comment]
I have issues similar to rggjan.  The lines which are covered and uncovered seem to be off by 1.  It shows the method definition (def foo) as uncovered, but then code inside the method as covered (impossible).

**Comment by abedra** [comment]
As I have mentioned in other issues the 1.9 support is experimental.  Patches are more than welcome.

**Comment by jmthomas** [comment]
What is the status of thread coverage in rcov? It doesn't appear that newly spawned threads in 1.9.1 show up with coverage.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Is this gem no longer maintained?

**Comment by jmthomas** [comment]
I'd try http://github.com/markbates/cover_me or http://github.com/colszowka/simplecov. All the examples are geared towards rails but either should work. Hopefully one will rise to the top in time.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Thanks a lot!

**Comment by rsanheim** [comment]
RCov does not, and will not support C based Ruby 1.9.x implementations due to significant changes between 1.8 and 1.9.  

We recommend looking into SimpleCov (http://www.rubyinside.com/simplecov-a-powerful-straightforward-ruby-1-9-code-coverage-tool-3712.html) or CoverMe (http://www.metabates.com/2010/08/13/coverme-code-coverage-for-ruby-1-9/) as options for Ruby 1.9.
